# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='nome')),
                ('birthday', models.DateField(verbose_name='data nascimento')),
                ('age', models.PositiveIntegerField(verbose_name='idade')),
                ('period', models.CharField(choices=[('manha', 'Matutino'), ('tarde', 'Diurno')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'filhos',
                'verbose_name': 'filho',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='nome')),
                ('prefixmobile', models.CharField(max_length=2, verbose_name='DDD')),
                ('mobile', models.CharField(max_length=9, verbose_name='celular')),
                ('prefixphone', models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, verbose_name='telefone')),
                ('city', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais')], max_length=50, verbose_name='cidade')),
                ('child', models.ManyToManyField(related_name='filhos', to='profile.Child')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pais',
                'verbose_name': 'pais',
                'ordering': ['fullname', 'city'],
            },
        ),
    ]
