# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 11:35
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='nome')),
                ('birthday', models.DateField(verbose_name='data nascimento')),
                ('age', models.PositiveIntegerField(verbose_name='idade')),
                ('period', models.CharField(choices=[('manha', 'Matutino'), ('tarde', 'Diurno')], max_length=10)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imagem')),
            ],
            options={
                'verbose_name_plural': 'filhos',
                'verbose_name': 'filho',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name_plural': 'cidades',
                'verbose_name': 'cidade',
                'ordering': ['uf', 'state'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='nome')),
                ('prefixmobile', models.CharField(max_length=2, verbose_name='DDD')),
                ('mobile', models.CharField(max_length=9, verbose_name='celular')),
                ('prefixphone', models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, verbose_name='telefone')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('child', models.ManyToManyField(related_name='filhos', to='profile.Child')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.City')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Responsaveis',
                'verbose_name': 'Responsavel',
                'ordering': ['fullname', 'city'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameschool', models.CharField(max_length=100, verbose_name='Nome Escola')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('addressNumber', models.CharField(max_length=4, verbose_name='Numero')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.City')),
            ],
            options={
                'verbose_name_plural': 'escolas',
                'verbose_name': 'escola',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.School'),
        ),
    ]
