# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20171114_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameschool', models.CharField(max_length=100, verbose_name='Nome Escola')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('addressNumber', models.CharField(max_length=4, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='profile.School'),
            preserve_default=False,
        ),
    ]
