# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 11:24
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fullname', models.CharField(max_length=100, verbose_name='nome')),
                ('category', models.CharField(max_length=3, verbose_name='Categoria')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.City')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.School')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typevehicle', models.CharField(choices=[('micro', 'Micro-Onibus'), ('min', 'Mini-Van')], max_length=10, verbose_name='Tipo Veiculo')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidade')),
                ('isDeficiente', models.BooleanField(default=False, verbose_name='Deficiente')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ManyToManyField(related_name='veiculos', to='vehicle.Vehicle'),
        ),
    ]
