# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:54
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fullname', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contactNumberDDD', models.CharField(max_length=5, verbose_name='DDD')),
                ('contactNumber', models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero Fixo')),
                ('contactNumberMobile', models.CharField(max_length=9, verbose_name='Numero Celular')),
                ('categoryHab', models.CharField(max_length=2, verbose_name='Categoria Habilitação')),
                ('createdIn', models.DateField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.City', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typevehicle', models.CharField(choices=[('micro', 'Micro-Onibus'), ('min', 'Mini-Van')], max_length=10, verbose_name='Tipo Veiculo')),
                ('isDeficiente', models.BooleanField(default=False, verbose_name='Deficiente')),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('parents', models.ManyToManyField(related_name='parents', to='profile.Parent', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='vehicle.Vehicle', verbose_name='veiculo'),
        ),
    ]
