# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='cidade',
            new_name='city',
        ),
    ]
